apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mywebapp-deployment
  labels:
    app:  mywebapp
spec:
  selector:
    matchLabels:
      app: mywebapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mywebapp
    spec:
      containers:
      - name:  mywebapp
        image:  santoshgoswami/mywebapp:latest
      nodeSelector:
        deploy: mywebapp
#        readinessProbe:
#          httpGet:
#            path: /WebApp/
#            port: 8080
#          initialDelaySeconds: 5
#          timeoutSeconds: 2
#          successThreshold: 1
#          failureThreshold: 3
#          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: mywebapp
  type: NodePort
  ports:
  - name: mywebapp
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31200
