apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mywebapp-deployment
  labels:
    app:  mywebapp
spec:
  selector:
    matchLabels:
      app: mywebapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  mywebapp
    spec:
      containers:
      - name:  mywebapp
        image:  santoshgoswami/mywebapp:latest
      nodeSelector:
        deploy: mywebapp
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: mywebapp
  type: NodePort
  ports:
  - name: mywebapp
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31200
